# Generated by Django 5.1.4 on 2025-02-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0005_videolog_batch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolog',
            name='file_audio_quality',
            field=models.CharField(default='192', max_length=5),
        ),
    ]
